### ISSUE TITLE
Non-recognised timezones

### ISSUE THREAD

**Issue by williamjcm** [JellyWX/reminder-bot#5]
I have a private Discord server, and all members (including me) live in France.

France is part of the CET (Central European Time, UTC+01:00) timezone, or CEST (Central European Summer Time, UTC+02:00) when DST is in effect (it is as of this writing).

While I can set the offset manually using `$timezone +2`, writing `$timezone CEST` makes the bot respond with `Sorry, that timezone isn't recognized. Please use a 3/4 letter code or a single negative or positive number.`

**Comment by JellyWX** [comment]
I see... testing now it seems quite a few timezones are missing. Currently, we're using the list of timezones present at https://github.com/dmfilipenko/timezones.json. I've had issues with this list before and I'll look into a replacement. Thank you for your report. If you wish to make a PR, the timezones are read from the file `EXT/timezones.json`

**Comment by williamjcm** [comment]
I'll look into it.

Could you please give me a very quick tutorial to pull requests ? I never used that feature before.

**Comment by JellyWX** [comment]
I think, you press the `fork` button to get a copy and make edits like normal. Then, in your fork, there should be an `open PR` or `merge` button or something which you press and itll send you to a screen to make a PR. I havent done it that much so im not really sure, sorry 

In the future, i think i'll replace the current TZ feature with the pytz module which can detect things like DST

**Comment by JellyWX** [comment]
Closing issue. Next update times will be done using PYTZ. A full list of PYTZ timezones is available at https://gist.github.com/heyalexej/8bf688fd67d7199be4a1682b3eec7568

**Comment by williamjcm** [comment]
Got it. Thanks.

**Comment by williamjcm** [comment]
Thanks for switching the timezone module.

Being able to use the `Europe/Paris` timezone makes it even more easier, as I don't even need to handle DST anymore.
